apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtmp-worker
spec:
  replicas: 0
  selector:
    matchLabels:
      app: rtmp-worker
  template:
    metadata:
      labels:
        app: rtmp-worker
    spec:
      containers:
      - name: worker
        image: liveedgecast-worker:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1935
        env:
        - name: RTMP_PUSH_URL
          valueFrom:
            secretKeyRef:
              name: liveedgecast-secrets
              key: rtmp-push-url
