apiVersion: v1
kind: Service
metadata:
  name: rtmp-worker
spec:
  type: ClusterIP
  selector:
    app: rtmp-worker
  ports:
  - port: 1935
    targetPort: 1935
    name: rtmp
  # Configuração para session affinity (opcional)
  # sessionAffinity: ClientIP
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 10800
