apiVersion: v1
kind: Service
metadata:
  name: rtmp-controller
  namespace: media
spec:
  selector: { app: rtmp-controller }
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
