apiVersion: v1
kind: ServiceAccount
metadata:
  name: rtmp-controller
  namespace: media
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rtmp-controller-role
  namespace: media
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rtmp-controller-binding
  namespace: media
subjects:
  - kind: ServiceAccount
    name: rtmp-controller
    namespace: media
roleRef:
  kind: Role
  name: rtmp-controller-role
  apiGroup: rbac.authorization.k8s.io
