apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveedgecast-deployment
  labels:
    app: liveedgecast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liveedgecast
  template:
    metadata:
      labels:
        app: liveedgecast
    spec:
      containers:
      - name: liveedgecast
        image: liveedgecast:latest  # Image built from local Dockerfile
        imagePullPolicy: IfNotPresent
        env:
        - name: RTMP_PUSH_URL
          valueFrom:
            secretKeyRef:
              name: liveedgecast-secrets
              key: rtmp-push-url
        ports:
        - containerPort: 1935
          name: rtmp
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        command: ["/entrypoint.sh"]
        args: ["nginx", "-g", "daemon off;"]
      volumes: []
      restartPolicy: Always
