apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: liveedgecast-rtmp-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: liveedgecast-deployment
  minReplicaCount: 0
  maxReplicaCount: 10
  pollingInterval: 15
  cooldownPeriod: 300
  fallback:
    failureThreshold: 3
    replicas: 0
  triggers:
  - type: external
    metadata:
      scalerAddress: "liveedgecast-service:8080"
      metricName: "rtmp_connections"
      threshold: "1"