apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: media
  labels:
    app: proxy
spec:
  type: LoadBalancer
  selector: { app: proxy }
  sessionAffinity: None
  ports:
    - name: rtmp
      port: 1935
      targetPort: 1935
      protocol: TCP
