apiVersion: v1
kind: Service
metadata:
  name: rtmp-proxy
  namespace: media
  labels:
    app: rtmp-proxy
spec:
  type: LoadBalancer   # ou NodePort, conforme seu cluster
  selector: { app: rtmp-proxy }
  ports:
    - name: rtmp
      port: 1935
      targetPort: 1935
      protocol: TCP
    - name: metrics
      port: 9113
      targetPort: 9113
      protocol: TCP
