apiVersion: v1
kind: Service
metadata:
  name: proxy-entry
  namespace: media
  labels:
    app: proxy-lb
spec:
  type: NodePort
  selector:
    app: proxy-lb
  ports:
    - name: rtmp
      port: 1935
      targetPort: 1935
      nodePort: 31935
      protocol: TCP
