apiVersion: v1
kind: ConfigMap
metadata:
  name: rtmp-proxy-lb-config
  namespace: media
data:
  haproxy.cfg: |
    global
      log stdout format raw local0
      maxconn 4000

    defaults
      mode tcp
      log global
      option tcplog
      timeout connect 5s
      timeout client 2m
      timeout server 2m

    resolvers kube
      nameserver dns1 kube-dns.kube-system.svc.cluster.local:53
      resolve_retries 3
      timeout resolve 1s
      timeout retry 1s
      hold valid 10s

    frontend rtmp_in
      bind *:1935
      default_backend rtmp_back

    backend rtmp_back
      balance leastconn
      option tcp-check
      server-template proxy 10 rtmp-proxy-headless.media.svc.cluster.local:1935 check resolvers kube init-addr libc,none
