apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: media
  labels:
    app: proxy
spec:
  type: LoadBalancer
  selector: { app: proxy }
  sessionAffinity: None
  ports:
    - name: rtmp
      port: 1935
      targetPort: 1935
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-internal
  namespace: media
  labels:
    app: proxy
spec:
  type: ClusterIP
  selector: { app: proxy }
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
