apiVersion: v1
kind: Service
metadata:
  name: rtmp-backend
  namespace: media
spec:
  selector: { app: rtmp-worker }
  ports:
    - name: rtmp
      port: 1935
      targetPort: 1935
      protocol: TCP
