apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtmp-worker
  namespace: media
spec:
  # replicas controlled by KEDA - starts at 0
  replicas: 0
  selector:
    matchLabels: { app: rtmp-worker }
  template:
    metadata:
      labels: { app: rtmp-worker }
    spec:
      containers:
        - name: rtmp
          image: liveedgecast-rtmp:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 1935
              name: rtmp
              protocol: TCP
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - name: cfg
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          readinessProbe:
            tcpSocket: { port: 1935 }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            tcpSocket: { port: 1935 }
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: cfg
          configMap: { name: rtmp-worker-nginx-conf }
