apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtmp-edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtmp-edge
  template:
    metadata:
      labels:
        app: rtmp-edge
    spec:
      containers:
      - name: edge
        image: liveedgecast-edge:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1935
          name: rtmp
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: nginx-config
        configMap:
          name: rtmp-edge-config
