apiVersion: v1
kind: Service
metadata:
  name: rtmp-edge
spec:
  type: LoadBalancer
  ports:
  - port: 1935
    targetPort: 1935
    name: rtmp
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: rtmp-edge
